sources:
  - name: MyGraphQLApi
    handler:
      graphql:
        endpoint: https://graphql.contentful.com/content/v1/spaces/mivicpf5zews/environments/dev
        schemaHeaders:
          {
            authorization: Bearer ffb6d2e75bdeb11580a166b1856d1b183e180c6da95a97998ab50cd12ad9eb85,
          }
        operationHeaders:
          {
            authorization: Bearer ffb6d2e75bdeb11580a166b1856d1b183e180c6da95a97998ab50cd12ad9eb85,
          }
    transforms:
      - cache:
          - field: Query.homePage
            cacheKey: entry-{args.id}-{args.locale}
            invalidate:
              effectingOperations:
                - operation: Mutation.updateEntry
                  matchKey: entry-{args.id}-{args.locale}
additionalTypeDefs: |
  type Mutation {
    updateEntry(id: String!, locale: String!): Float
  }
additionalResolvers:
  - ./src/additional-resolvers.js
